services:
  REDACTED_DB_NAME:
    # https://hub.docker.com/_/mediawiki
    image: mediawiki:1.44.0
    container_name: ${CONTAINER_NAME:?}
    restart: unless-stopped
    environment:
      MEDIAWIKI_DB_HOST: db
      MEDIAWIKI_DB_TYPE: ${DB_TYPE:?}
      MEDIAWIKI_DB_NAME: ${DB_NAME:?}
      MEDIAWIKI_DB_USER: ${DB_USER:?}
      MEDIAWIKI_DB_PASSWORD: ${DB_PASSWD:?}
    labels:
      - traefik.enable=true
      - traefik.http.services.${CONTAINER_NAME:?}.loadbalancer.server.port=80
      - traefik.http.routers.${CONTAINER_NAME:?}.rule=Host(`${SUBDOMAIN:?}.${TRAEFIK_DOMAIN:?}`)
      - traefik.http.routers.${CONTAINER_NAME:?}.entrypoints=websecure
    networks:
      - mediawiki
      - traefik
    ports:
      - 8081:80
    volumes:
      - ${IMAGES_DIR}:/var/www/html/images
      # Comment out LocalSettings.php on the first time run
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    depends_on:
      - db
  
  db:
    # Official MariaDB image
    image: mariadb:11.4
    container_name: ${CONTAINER_NAME:?}-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_NAME:?}
      MARIADB_USER: ${DB_USER:?}
      MARIADB_PASSWORD: ${DB_PASSWD:?}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${DB_DIR}:/var/lib/mysql
    networks:
      - mediawiki

networks:
  mediawiki:
    name: ${CONTAINER_NAME:?}
  traefik:
    external: true
