services:
  mediawiki:
    # https://hub.docker.com/_/mediawiki
    image: mediawiki:1.44.0
    container_name: mediawiki
    restart: unless-stopped
    # environment:
    #   MEDIAWIKI_SITE_NAME: TestWiki
    #   MEDIAWIKI_DB_HOST: mediawiki-db
    #   MEDIAWIKI_DB_TYPE: ${DB_TYPE:?}
    #   MEDIAWIKI_DB_NAME: ${DB_NAME:?}
    #   MEDIAWIKI_DB_USER: ${DB_USER:?}
    #   MEDIAWIKI_DB_PASSWORD: ${DB_PASSWD:?}
    networks:
      - mediawiki
    ports:
      - 8080:80
    volumes:
      - ./images:/var/www/html/images
      - db:/var/www/data
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    # depends_on:
    #   - db
  
#   db:
#     # https://hub.docker.com/r/bitnami/mariadb
#     image: bitnami/mariadb:11.8.2
#     container_name: mediawiki-db
#     restart: unless-stopped
#     environment:
#       MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWD:?}
#       MARIADB_USER: ${DB_USER:?}
#       MARIADB_PASSWORD: ${DB_PASSWD:?}
#       MARIADB_DATABASE: ${DB_NAME:?}
#     networks:
#       - mediawiki
#     volumes:
#       - db:/var/lib/mysql

networks:
   mediawiki:
    name: mediawiki

volumes:
  db:
    name: mediawiki-db